# we will toke the advatage of th gcr.io builder as pre-build builder
# it allow us to build and tag and push docker images directly to google cloud build

#reservations
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/sleepr-456713/reservations/production', '-f','apps/reservations/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/sleepr-456713/reservations/production']

#payments
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/sleepr-456713/payments/production', '-f','apps/payments/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/sleepr-456713/payments/production']

#auth
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/sleepr-456713/auth/production', '-f','apps/auth/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/sleepr-456713/auth/production']

#notifications
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/sleepr-456713/notifications/production', '-f','apps/notifications/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/sleepr-456713/notifications/production']
  